name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Static Code Analysis and Style Checks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Step 3: Install Python dependencies for linting
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 4: Run Flake8 for static code analysis
      - name: Run Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Run Stylelint for CSS style checks
      - name: Style Checks
        uses: github/super-linter@v5  # Use an updated Stylelint-compatible action
        with:
          file-types: 'css'
          lint-options: '--config .stylelintrc.json'  # Optional configuration file

  build:
    name: Build the Application
    runs-on: ubuntu-latest
    needs: lint

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the application
      - name: Build the Application
        run: |
          echo "Building the Python web application..."
